# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "gusztavvargadr/w16s"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    
    # Name in the VirtualBox Gui
    config.vm.provider "virtualbox" do |v|
      v.name = "server1"
    end

    config.vm.network "private_network", ip: "192.168.56.12"
    
    # Computername within windows guest
    config.vm.hostname = "server1"

    config.vm.provision "script_a", type: "shell" do |s|
      s.path = "provision-modules.ps1"
      s.upload_path = "C:\\tmp\\provision-modules.ps1"
    end
    
    config.vm.provision "script_b", type: "shell" do |s|
      s.path = "provision-dsc.ps1"
      s.upload_path = "C:\\tmp\\provision-dsc.ps1"
    end
        
    config.vm.provision "script_c", type: "shell" do |s|
      s.path = "provision-domain.ps1"
      s.upload_path = "C:\\tmp\\provision-domain.ps1"
    end
    
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    
      # Customize the amount of memory on the VM:
    vb.memory = "1024"
    end

  end
